#!/bin/bash -e

# Shell Script that will auto-call ansible-playbook for me

if [[ $EUID == 0 ]]; then
    echo ""
    echo "Sorry, can't use sudo."
    exit 2
    press_enter
    exit 1
fi

gen_scripts=/Users/$USER/git/generalscripts

function help_text ()
    {
        echo "My personal shortcutting ansible stuffs!"
        echo ""
        echo "Usage: ans-apt [-ul --update-linux] [-rl --reboot-linux] [-rv --reboot-virtual] [-h --help]"
        echo ""
        echo "Options:"
        echo "    -ul, --update-linux     : Updates all Linux Machines"
	    echo "	  -uv, --update-virtual   : Updates all Virtual Machines"
        echo ""
        echo "    -rl, --reboot-linux     : Reboots all Linux Machines"
        echo "    -rv, --reboot-virtual   : Reboots all Virtual Machines"
        echo ""
        echo "    -sl, --shutdown-linux   : Shutsdown all Linux Machines"
        echo "    -sv, --shutdown-virtual : Shutsdown all Virtual Machines"
        echo ""
        echo "    -h,  --help             : this help"
    }

case "$1" in
    -ul | --update-linux )
        echo "Updating Linux apt-get";
        ansible-playbook -i "$gen_scripts/hosts"  "$gen_scripts/ansible/apt_basic.yml"
        ;;
    -uv | --update-virtual )
        echo "Updating only Virtual Machines";
        ansible-playbook -i "$gen_scripts/hosts"  "$gen_scripts/ansible/apt_basic.yml" --limit=virtual
        ;;
    -rl | --reboot-linux )
        echo "Rebooting all Linux Machines";
        ansible-playbook -i "$gen_scripts/hosts" "$gen_scripts/ansible/restart-apt.yml"
        ;;
    -rv | --reboot-virtual )
        echo "Rebooting only Virtual Machines";
        ansible-playbook -i "$gen_scripts/hosts" "$gen_scripts/ansible/restart-apt.yml" --limit=virtual
        ;;
    -m | --monit-reload )
        echo "Reloads monit on all linux machines";
        ansible -i "$gen_scripts/hosts" linux -s -m service -a 'name=monit state=reloaded'
        ;;
    -sl | --shutdown-linux )
        echo "Shutting down all linux devices";
        ansible -i "$gen_scripts/hosts" linux -s -a 'shutdown -h now'
        ;;
    -sv | --shutdown-virtual )
        echo "Shutting down all Virtual Machines";
        ansible -i "$gen_scripts/hosts" virtual -s -a 'shutdown -h now'
        ;;
    -h | --help )
        help_text &&
        exit 0
        ;;
    * )
        help_text &&
        exit 0

esac
