---
# Ansible-Playbook for Headphones installation

- name: Clone headphones repo
  git:
    repo: https://github.com/rembo10/headphones.git
    dest: "{{ git_loc }}/headphones"
    update: yes
  notify: restart headphones

- name: Confirm Correct ownership of HP repo
  file:
    path: "{{ git_loc }}/headphones"
    owner: jpartain89
    group: jpartain89
    recurse: yes
    state: directory

- name: Symlink HP Repo to /opt
  file:
    src: "{{ git_loc }}/headphones"
    dest: /opt/headphones
    state: link
    owner: jpartain89
    group: jpartain89

- name: Copy the default HP /etc/default file
  copy:
    src: hp_default
    dest: /etc/default/headphonesw
    owner: root
    group: root
    mode: 0644

- name: Link the Ubuntu init.d file
  file:
    src: /opt/headphones/init-scripts/init.ubuntu
    dest: /etc/init.d/headphones
    state: link
    owner: root
    group: root
    mode: 0755
  notify: start headphones

- name: Add HP to UFW
  ufw:
    state: enabled
    rule: allow
    port: 8181
