---
# Ansible-Playbook for PlexPy

- name: Make sure PlexPy user exists
  user:
    name: plexpy
    state: present
    system: yes
    groups: vboxsf
    group: nogroup

- name: Clone PlexPy GitHub Repo
  git:
    repo: https://github.com/drzoidberg33/plexpy.git
    dest: "{{ git_loc }}/plexpy"
    update: yes
  notify: restart plexpy

- name: Update Ownership of PlexPy git Repo
  file:
    path: "{{ git_loc }}/plexpy"
    owner: plexpy
    group: nogroup
    recurse: yes
    state: directory

- name: Symlink PlexPy Repo to /opt
  file:
    src: "{{ git_loc }}/plexpy"
    dest: /opt/couchpotato
    state: link
    owner: plexpy
    group: nogroup

- name: Copy Default PlexPy File
  copy:
    src: plexpy_default
    dest: /etc/default/plexpy
    owner: root
    group: root
    mode: 0644

- name: Link the ubuntu init.d file
  file:
    src: /opt/plexpy/init-scripts/init.ubuntu
    dest: /etc/init.d/plexpy
    state: link
    mode: 0755
    owner: root
    group: root
  failed_when: False
  notify: start plexpy

- name: Add PlexPy to UFW
  ufw:
    state: enabled
    rule: allow
    port: 8182
