---
# rpi.yml

- hosts: rpi
  become: yes

  vars:
    user: jpartain89
    git_loc_mac: /Users/{{ user }}/git
    git_loc_rpi: /home/{{ user }}/git
    git_http_jp: https://jpartain89@github.com/jpartain89/

  tasks:
    - include: tasks/monit.yml

    - name: Make sure jpartain89 is present
      user:
        name: "{{ user }}"
        state: present

    - name: Install sudo, nano, and others
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      items:
        - sudo
        - nano
        - make
        - build-essential
        - python
        - python-dev
        - git
        - rpi-update
        - raspi-config

    - name: Linux_Dotfiles Cloning
      git:
        repo: "{{ git_http_jp }}/linux_dotfiles.git"
        dest: "{{ git_loc_rpi }}/linux_dotfiles"
        update: yes

    - name: generalscripts cloning
      git:
        repo: "{{ git_http_jp }}/generalscripts"
        dest: "{{ git_loc_rpi }}/generalscripts"
        update: yes
