---
# ansible/pip/tasks/main.yml

- name: Make sure dotfiles repo is updated
  git:
    repo: https://jpartain89@github.com/jpartain89/{{ dot_dir_name }}.git
    dest: "{{ git_loc }}/{{ dot_dir_name }}"
    force: yes
    update: yes

- name: Make sure standard pip stuff is installed
  pip:
    requirements: "{{ git_loc }}/{{ dot_dir_name }}/requirements.txt"

- name: Pip install from Already-Installed Pip List
  shell: "pip install -U $(pip list --format=legacy | awk '{ print $1}')"
  register: pip_install_formatted
  failed_when: False

- name: Show Pip install Output
  debug: var=pip_install_formatted.stdout_lines
