---
# file: group_vars/local-macos

user_home: /Users/{{ username }}
dot_dir_name: macos_dotfiles
pip_requirements: requirements-macOS.txt

ssh_dot: config

dotfiles_to_sync:
  - { src: "{{ dotfiles_directory }}/etc/ssh/*", dest: /etc/ssh/ }
  - { src: "{{ dotfiles_directory }}/etc/ssh/*", dest: /usr/local/etc/ssh/ }
  - { src: "{{ dotfiles_directory }}/etc/sudoers*", dest: /etc/ }
  - { src: "{{ dotfiles_directory }}/etc/paths*", dest: /etc/ }
  - { src: "{{ dotfiles_directory }}/etc/ansible", dest: /etc/ }
