---
# nginx/tasks/main.yml

- name: Configure NGINX Repos on Ubuntu
  apt_repository:
    repo: 'ppa:nginx/development'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: yes
  notify:
    - restart nginx

- name: Sync to /etc/nginx
  synchronize:
    src: "{{ nginx_source_location }}/nginx_conf/"
    dest: /etc/nginx
  notify:
    - restart nginx

- name: Sync html Files
  synchronize:
    src: "{{ nginx_source_location }}/html"
    dest: /var/www/
  notify:
    - restart nginx

- name: Test NGINX Config
  shell: 'nginx -t'
  args:
    executable: /bin/bash
  #changed_when: False
  register: nginx_test
