---
# monit/tasks/monit_git.yml

- name: Clone/Update Monit's git repo
  git:
    repo: https://tildeslash@bitbucket.org/tildeslash/monit.git
    dest: "{{ git_file_loc }}/monit"
    force: yes
    update: yes
  register: monit_git_update

- include: build_monit.yml
  when: monit_git_update|


- name: Configure
  shell: './configure --enable-optimized --enable-profiling'
