---
# monit/tasks/main.yml

- name: Prerequisites
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libtool
    - gcc
    #- gcc-4.9
    - gcc-4.9-base
    #- gcc-4.9-source
    - bison
    - libbison-dev
    - flex
    - libfl-dev

- name: Clone Git Repo/Force Clone if current exists
  git:
    repo: https://tildeslash@bitbucket.org/tildeslash/monit.git
    dest: ~/git/monit
    force: yes

- name: Bootstrap
  shell: './bootstrap'
  args:
    chdir: ~/git/monit

- name: Configure
  shell: './configure --enable-optimized --enable-profiling'
  args:
    chdir: ~/git/monit

- name: Make
  shell: 'make'
  args:
    chdir: ~/git/monit

- name: Make Install
  become: yes
  shell: 'make install'
  args:
    chdir: ~/git/monit

- name: Stop Monit
  become: yes
  shell: 'killall monit'

- name: Start Monit
  become: yes
  command: '/usr/local/bin/monit'
