---
# Ansible Play to update, upgrade, dist-upgrade, and autoremove --purge

- hosts: linux
  become: yes

  tasks:
    - name: Make Sure Basic apt Programs are Installed and Update Cache
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 86400
      with_items:
        - aptitude
        - apt
        - apt-utils

    - name: Run Basic, Safe, Full and Dist Upgrade with apt Module
      apt: upgrade="{{ item }}"
      with_items:
        - yes
        - safe
        - full
        - dist
      register: _upgrade_apt
      failed_when: False

    - debug: var=_upgrade_apt
      when: _upgrade_apt|changed

    - name: Autoremove Command in apt Module
      apt: autoremove=yes
      register: _autoclean_apt
      failed_when: False

    - debug: var=_autoclean_apt
      when: _autoclean_apt|changed

    - name: Run my AutoRemove apt Command String
      shell: 'apt-get autoremove --purge -y $(dpkg --list | grep "^rc" | awk "{print $2}")'
      register: _autoremove_rc_apt
      failed_when: False

    - debug: var=_autoremove_rc_apt
      when: _autoremove_rc_apt|changed
