---
# Ansible Play to update, upgrade, dist-upgrade, and autoremove --purge

- hosts: linux
  become: yes

  tasks:
    - name: Linux | Install Aptitude and Update Apt Cache
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 86400
      with_items:
        - aptitude
        - apt
        - apt-utils

    - name: Linux | Apt Upgrade, Dist-Upgrade
      apt: upgrade="{{ item }}"
      with_items:
        - yes
        - safe
        - full
        - dist
      register: upgrade_apt
      ignore_errors: True

    - name: Linux | Show upgrade_apt Output
      debug: var=upgrade_apt
      when: upgrade_apt|changed

    - name: Linux | Run Apt AutoClean (Autoremove Keyword for Ansible)
      apt: autoremove=yes
      register: autoclean_apt
      ignore_errors: True

    - name: Linux | Show Apt AutoClean Output
      debug: var=autoclean_apt
      when: autoclean_apt|changed

    - name: Linux | Autoremove "rc" Labeled Apps using the Shell
      shell: 'apt autoremove --purge -y $(dpkg --list | grep `^rc` | awk `{print $2}`)'
      register: autoremove_rc_apt
      ignore_errors: True

    - name: Linux | Show AutoRemove "rc" Apps
      debug: var=autoremove_rc_apt
      when: autoremove_rc_apt|changed
