---
# Ansible Play to update, upgrade, dist-upgrade, and autoremove --purge

- hosts: linux
  become: yes

  tasks:
    - name: sudo apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 7200

    - name: sudo apt-get upgrade
      apt:
        upgrade: full
      register: upgrade_apt

    - name: Show apt-get upgrade Output
      debug: var=upgrade_apt.stdout_lines

    - name: sudo apt-get dist-upgrade
      apt:
        upgrade: dist
      register: dist_apt

    - name: Show apt-get dist-upgrade Output
      debug: var=dist_apt.stdout_lines

    - name: sudo apt-get autoclean
      shell:
        'apt-get autoclean -y'
      register: autoclean_apt

    - name: Show apt-get autoclean Output
      debug: var=autoclean_apt.stdout_lines

    - name: AutoRemove Apt Packages
      shell:
        'apt-get autoremove -y'
      register: ara
      changed_when: False

    - name: Show Autoremove Output
      debug: var=ara.stdout_lines

    - name: Autoremove "rc" labeled apps
      shell:
        'apt-get autoremove --purge -y $(dpkg --list | grep `^rc` | awk `{print $2}`)'
      register: autoremove_rc_apt

    - name: Show autoremove rc apps
      debug: var=autoremove_rc_apt.stdout_lines

- hosts: macos
  become: no

  tasks:
  - name: Running brewdate
    shell: '/usr/local/bin/brewdate'
