---

- hosts: macos
  become: no

  tasks:
    - name: macOS | Running "brewdate"
      command: 'brewdate'
      args:
        executable: /bin/bash
      register: _brewdate
      ignore_errors: True

    - debug: var=_brewdate
