---

- hosts: macos
  become: no

  vars:
    - GIT_HOME: /Users/jpartain89/git

  tasks:
    - name: macOS | Running "brewdate"
      shell: '~/bin/brewdate'
      args:
        executable: /bin/bash
      register: _brewdate
      ignore_errors: True

    - name: macOS | Show brewdate Output
      debug: var=_brewdate
      when: _brewdate|failed

    - name: macOS | Run Pip Installer Against Requirements File
      pip:
        requirements: "{{ GIT_HOME }}/macOS-First-Steps/requirements.txt"
        executable: "{{ item }}"
      with_items:
        - pip2
        - pip3
      register: pip_requirements
      ignore_errors: True

    - name: macOS | Show pip_requirements Output
      debug: var=pip_requirements
      when: pip_requirements|failed
