---

# The `become` line is required to make sure these do not run with sudo
- hosts: macos
  become: no

  tasks:
    - name: Running brewdate
      shell: 'brewdate'
      args:
        executable: /bin/bash
      register: _brewdate
      failed_when: False

    - debug: var=_brewdate.stdout_lines

    - name: Running softwareupdate Command
      shell: 'softwareupdate -ia'
      args:
        executable: /bin/bash
      register: _softwareupdate
      failed_when: False

    - debug: var=_softwareupdate.stdout_lines
