---

- hosts: macos
  become: no

  tasks:
    - name: macOS | Running "brewdate"
      shell: '~/bin/brewdate'
      args:
        executable: /bin/bash
      register: _brewdate
      ignore_errors: True

    - name: macOS | Show brewdate Output
      debug: var=_brewdate
      when: _brewdate|failed
