---

- hosts: macos
  become: no
  environment:
    PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar"

  tasks:
    - name: Running "brewdate"
      shell: 'brewdate'
      args:
        executable: /bin/bash
      register: _brewdate
      failed_when: False

    - debug: var=_brewdate.stdout_lines
