---

- hosts: macos
  become: no

  tasks:
    - name: Running "brewdate"
      shell: 'brewdate'
      args:
        executable: /bin/bash
      register: _brewdate
      ignore_errors: True
      environment:
        PATH: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar"

    - debug: var=_brewdate.stdout_lines
