---
# Ansible Play to run map-pull-sub

- hosts: all
  remote_user: jpartain89

  vars:
    - default_git_repo_name: conffiles
    - default_git_repo_location: "{{ git_loc }}/{{ default_git_repo_name }}"

  tasks:
    - name: Confirm the {{ default_git_repo_name }} Repo is Downloaded
      git:
        repo: "https://github.com/jpartain89/conffiles.git"
        dest: "{{ git_loc }}/conffiles"
        update: yes
      ignore_errors: True

    - name: Run map-pull-sub from within default_git_repo Location
      shell: 'git -C {{ git_loc }}/conffiles map {{ item }}'
      args:
        executable: /bin/bash
      with_items:
        - pull
        - 'fetch --all'
        - 'submodule update --init --recursive'
      register: map_pull_sub_reg
      ignore_errors: true

    - debug: var=map_pull_sub_reg
