---
# common installs

- hosts: linux

  tasks:
    - name: Clone Standard Github Repos
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        update: yes
      with_items:
          -
            repo: "{{ jp_git }}/conffiles.git"
            dest: "{{ git_loc }}/conffiles"
          -
            repo: "{{ jp_git }}/generalscripts.git"
            dest: "{{ git_loc }}/generalscripts"
          -
            repo: https://github.com/icefox/git-map.git
            dest: "{{ git_loc }}/git-map"
          -
            repo: "{{ jp_git }}/myfunctions.git"
            dest: "{{ git_loc }}/myfunctions"
          -
            repo: "{{ jp_git }}/{{ dotfiles_c }}.git"
            dest: "{{ git_loc }}/{{  dotfiles_c }}"

    - name: Run bootstrap.sh from dotfiles.
      shell: 'source "{{ git_loc }}/{{ dotfiles_c }}/bootstrap.sh"'
      args:
        executable: /bin/bash

    - name: Install apt-get Universal Requirements
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 7200
      when: ansible_os_family == "Debian"
      with_items:
        - git-core
        - libffi-dev
        - libssl-dev
        - zlib1g-dev
        - libxslt1-dev
        - libxml2-dev
        - python
        - python-pip
        - python-dev
        - python-pycurl
        - python-setuptools
        - python-imaging
        - build-essential
        - python2.7
        - apt-transport-https

    - name: Install Pip Requirements
      become: yes
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - lxml
        - cryptography
        - pyopenssl
        - pip
        - cffi
        - ndg-httpsclient
        - urllib3
        - speedtest-cli
