---
# file: requirements.yml

- hosts: linux

  tasks:
    - include: tasks/install-apt.yml
    - include: tasks/git-clone.yml
    - include: tasks/bootstrap.yml
    - include: tasks/pip-requirements.yml
