#!/bin/bash -e

SITE="jpcdi.com"
LE_LOC="/etc/letsencrypt"
LE_SITE="${LE_LOC}/live/${SITE}"

# Fix the permissions of the new files
chown -R jpartain89:jpartain89 "${LE_LOC}"

# Add updates to git
git add "${LE_LOC}"
git -C "$LE_LOC" commit -m "Certs are renewed on $(date)."
git -C "$LE_LOC" push

# copy the files
cp "${LE_SITE}/cert.pem" "/etc/ssl/certs/${SITE}.cert.pem"
cp "${LE_SITE}/fullchain.pem" "/etc/ssl/certs/${SITE}.fullchain.pem"
cp "${LE_SITE}/privkey.pem" "/etc/ssl/private/${SITE}.privkey.pem"

# adjust permissions of the private key
chown :ssl-cert "/etc/ssl/private/${SITE}.privkey.pem"
chmod 640 "/etc/ssl/private/${SITE}.privkey.pem"
