#!/bin/bash -e

# https://sh.jpcdi.com/2ypfGq1

SITE="jpcdi.com"
LETSENCRYPT_GIT="/home/jpartain89/git/letsencrypt"
LE_SITE="${LETSENCRYPT_GIT}/live/${SITE}"
LOGDIR="${LETSENCRYPT_GIT}/logs"
LOGFILE="${LOGDIR}/after_certbot_renew.log"

PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

AUTO_GIT="$(command -v auto-git)"

# Fix the permissions of the new files
sudo chown -R jpartain89:jpartain89 "${LETSENCRYPT_GIT}"

# Add updates to git
"${AUTO_GIT}" "${LETSENCRYPT_GIT}" >>"$LOGFILE" 2>&1

if [ "$(command -v slapd)" ]; then
    # copy the files
    sudo cp "${LE_SITE}/cert.pem" "/etc/ssl/certs/${SITE}.cert.pem"
    sudo cp "${LE_SITE}/fullchain.pem" "/etc/ssl/certs/${SITE}.fullchain.pem"
    sudo cp "${LE_SITE}/privkey.pem" "/etc/ssl/private/${SITE}.privkey.pem"

    # adjust permissions of the private key
    sudo chown :ssl-cert "/etc/ssl/private/${SITE}.privkey.pem"
    sudo chmod 640 "/etc/ssl/private/${SITE}.privkey.pem"

    sudo systemctl restart slapd >/dev/null 2>&1
fi
