#!/bin/bash

# Wrapper script for dpkg allowing for multiple URL's along side
# local files with command line flags.

trap 'rm '

COUNT=0
for i in "$@"; do
    if [ "$(echo "$i" | grep http 2>&1 > /dev/null)" ] ; then
    #if [ $? == 0 ]; then
        URL="$URL $i"
        continue
    fi
    PASSTODPKG="$PASSTODPKG $i"
done

#Remove beginning and trailing space
URL=$(echo "$URL" | sed -e 's/^ //g' -e 's/ $//g')

if [ ! -z "$URL" ]; then
    for i in $URL; do
        TEMP_DEB="$(mktemp)"
        wget -O "$TEMP_DEB""$i"
    done
    dpkg "$PASSTODPKG" "$TEMP_DEB"
    rm -f "$TEMP_DEB"
else
    dpkg "$PASSTODPKG"
fi
