#!/bin/bash -e

USERNAME=jpartain89
source allunix

trap 'killall homebridge; exit $?' SIGHUP SIGINT SIGTERM

cd /usr/local/lib/node_modules/homebridge-wink &&
/usr/local/bin/homebridge -I -U /Users/jpartain89/.homebridge | timestamp 2>&1 &
echo $! > /var/run/homebridge.pid
