#!/bin/bash -e

PROGRAM_NAME="auto-handbrake"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILE="$1"

die() {
    echo "$program: $1" >&2
    exit "${2:-1}"
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

help() {
    cat << EOF
auto-handbrake [directory location]

This script is to automatically run HandBrakeCLI with specific preset settings. You need to include the directory location of the movies you want re encoded.
EOF
}

# This "auto-installs" git-autopull into /usr/local/bin for ya!
command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

PRESET="Apple 1080p60 Surround"
SOURCE="$FILE"

while [[ "$1" -ge 1 ]]; do
    case "$FILE" in
        -h ) help;;
        * ) help;;
    esac
done

while IFS= read -r line; do
    output="${line%\.[^.]*}.mp4"

    HandBrakeCLI -Z "${PRESET}" --input "${line}" \
        --output "${output}" < /dev/null &&

    rm "$line"

done < <(find "$SOURCE" \( -iname "*avi" -o -iname "*wmv" -o -iname "*mov" -o -iname "*flv" \) -exec echo {} \; )
