#!/bin/bash -e

#source /Users/jpartain89/bin/allunix

PATH="/Users/jpartain89/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar"

trap 'exit $?' SIGHUP SIGINT SIGTERM

( /sbin/mount | grep "on /Volumes/RAID_EXT" >/dev/null) || echo "RAID_EXT is missing. 
Exiting." exit 1

command -v gmvault >/dev/null 2>&1 ||  ( echo ""; echo "gmvault is missing, exiitng."; echo ""; exit 1 )

gmACCOUNTS=(
    jpartain89
    subFFbb89
    subkinkyboi89
)

function SYNCING() {
    for i in "${gmACCOUNTS[@]}"; do
        /usr/local/bin/gmvault sync "${i}@gmail.com" -d "/Volumes/RAID_EXT/backup/gmvault/${i}" -t "$SYNC_TYPE" -e -m &> /dev/null;
        wait;
        printf " ${i} done!\n";
    done && exit 0
}

if [ $# -lt 1 ]; then
    set quick;
fi

while [ $# -ge 1 ]; do
    case "$1" in
        full )
            SYNC_TYPE=full;
            SYNCING
        ;;
        quick )
            SYNC_TYPE=quick;
            SYNCING
        ;;
    esac
done

exit 0
