#!/bin/bash

PROGRAM_NAME="auto-handbrake"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILE="$1"

die() {
    echo "$program: $1" >&2
    exit "${2:-1}"
}

help() {
    cat << EOF
auto-handbrake [directory location]

This script is to automatically run HandBrakeCLI with specific preset settings.
You need to include the directory location of the movies you want re encoded.
EOF
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

# This "auto-installs" git-autopull into /usr/local/bin for ya!
command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

test -x "$(command -v HandBrakeCLI)" || die "Looks like HandBrakeCLI is missing."

general() {
    # These are the 'general' file extensions that I use.
    FIND_ARGS='\( -iname "*avi" -o -iname "*wmv" -o -iname "*mov" -o -iname "*flv"\)'
}

AVCHD() {
    # This is for running against AVCHD
    FIND_ARGS='-type d -iname "AVCHD"'
}

PRESET="Apple 1080p60 Surround"
SOURCE="$FILE"

while (( "$#" )); do
    case "$1" in
        -g | --general )
            current
            break
            ;;
        -d | --directory )
            DARG=$2 &&
            not_here &&
            break
            ;;
        -- ) # end argument parsing
            shift
            break
            ;;
        -* | --* ) # unsupported flags
            echo "Error: Unsupported flag $1" >&2;
            help;
            die "$@"
            ;;
        * ) # preserve positional arguments
            PARAMS="$PARAMS $1"
            shift
            ;;
    esac
done

while [[ "$?" -ge 1 ]]; do
    case "$FILE" in
        -h ) help;;
        * ) help;;
    esac
done

while IFS= read -r line; do
    output="${line%\.[^.]*}.mp4"

    HandBrakeCLI -Z "${PRESET}" --input "${line}" \
        --output "${output}" < /dev/null &&

    rm "$line"

done < <(find "$SOURCE" "${FIND_ARGS}" -exec echo {} \; )
