#!/bin/bash -e

export B2_ACCOUNT_ID=001363fdd9710cb0000000001
export B2_ACCOUNT_KEY=K001GHfv1fQ1YcOq2WYs1yrTjuxygO0
export RESTIC_PASSWORD=lover0778

RESTIC="/opt/bin/restic"
BUCKET="jpcdi-synRoot"
EXCLUDE_FILE="/opt/etc/restic/exclude.txt"
INCLUDE_FILE="/opt/etc/restic/include.txt"
KEEP_LAST="5"
KEEP_HOURLY="12"
KEEP_DAILY="7"
KEEP_WEEKLY="12"
KEEP_MONTHLY="6"
KEEP_YEARLY="5"

"${RESTIC}" -r b2:"${BUCKET}":/ --verbose backup --files-from "${INCLUDE_FILE}" --exclude-file "${EXCLUDE_FILE}" &&

"${RESITC}" -r b2:"${BUCKET}":/ --verbose forget \
    --keep-last "${KEEP_LAST}" \
    --keep-hourly "${KEEP_HOURLY}" \
    --keep_daily "${KEEP_DAILY}" \
    --keep-weekly "${KEEP_WEEKLY}" \
    --keep-monthly "${KEEP_MONTHLY}" \
    --keep-yearly "${KEEP_YEARLY}" \
    --prune
