#!/usr/bin/env bash
set -e

# This is to backup the general Plex directory once every 2 days.

# Copyright © 2019 JPCDI, JPartain89, Justin Partain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Program Info
PROGRAM_NAME="backup_plex"
REPO_NAME="generalscripts"
VERSION="1.0.0"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This "auto-installs"  into /usr/local/bin for ya!
command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

die() {
    echo "$PROGRAM_NAME: $1" >&2
    exit "${2:-1}"
}

trap 'die "Trap Called"' SIGHUP SIGINT SIGTERM

PATH="/usr/local/opt/python3/bin:/usr/local/opt/python3/libexec/bin:/usr/local/opt/python@2/bin:/usr/local/opt/python/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin:/usr/local/opt/go/libexec/bin"

__BACKUP_FROM="${HOME}/Library"
__BACKUP_TO="/Volumes/2TB_APFS/backup/Plex"
__BACKUP_FILE="com.plexapp.plexmediaserver.plist"
BACKUP_FROM_FILES="${__BACKUP_FROM}/Preferences/${__BACKUP_FILE}"
BACKUP_FROM_DIR="${__BACKUP_FROM}/ApplicationSupport/Plex Media Server"
BACKUP_TO_FILE="${__BACKUP_TO}/PlexBackup_$(date +"%m-%d-%Y").tar.gz"
LOGDIR="/usr/local/var/log/PlexBackup"

TAR="$(command -v tar)"

# This is to create the log directory, just in case
if [[ ! -d "${LOGDIR}" ]]; then mkdir "${LOGDIR}"; fi

# This is the actual TAR step
"${TAR}" vcfz "${BACKUP_TO_FILE}" "${BACKUP_FROM_DIR}" \
    > "${LOGDIR}/$(date +"%m-%d-%Y").log" 2>&1

# This is to copy the PLIST file for macOS
cp "${BACKUP_FROM_FILES}" "${__BACKUP_TO}/${__BACKUP_FILE}_$(date +"%m-%d-%Y")"
