#!/usr/bin/env bash -e

# Install and configure bind9 and isc-dhcp-server together.

sudo apt-get install -y bind9 isc-dhcp-server
if sudo rndc-confgen -a -b 512; then
    sudo rm /etc/bind/rndc.conf
    sudo cp /etc/bind/rndc.key /etc/dhcp/rndc.key
    sudo chown root:root /etc/dhcp/rndc.key
    sudo chmod 0640 /etc/dhcp/rndc.key
fi

sudo chown -R bind:bind /etc/bind

sudo usermod -aG bind root
sudo usermod -aG root bind
sudo usermod -aG bind jpartain89
sudo usermod -aG bind markdanielusa
