#!/bin/bash

# program info
PROGRAM_NAME="blocklist_down"
REPO_NAME="generalscripts"
VERSION="1.0.0"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

die() {
    echo "$PROGRAM_NAME: $1" >&2
    exit "${2:-1}"
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

if [[ $(hostname) != 'rpi35' ]]; then
    echo "So sorry! This can only be run on one machine! Exiting!"
    exit 1
fi

help() {
    cat << EOF

Usage:$PROGRAM_NAME

    $PROGRAM_NAME is to download all of the blocking lists from https://www.iblocklist.com/ and pipe them into a txt file residing on my web server for consumption by other systems.

    You have to include the location and file name of where you want the final file output to be.
EOF
exit 1
}

command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

CRON() {
    sudo sh -c 'cat << EOF > /etc/cron.d/blocklist_down
# This cron file is for calling my blocklist script for transmission.
SHELL=/bin/bash

0 */6 * * *  /usr/local/bin/blocklist_down
'
}

BLOCKLIST=/var/www/html/public/jp_full.txt
TRANSMISSION_HOST="jpartain89@192.168.0.15"

main() {
    # Link good as of June 2018
    # Download lists, unpack and filter, write to stdout
    curl -s https://www.iblocklist.com/lists.php \
        | sed -n "s/.*value='\(http:.*\?list=.*\)'.*/\1/p" \
        | xargs wget -O - \
        | gunzip \
        | egrep -v '^#'
}

if [[ ! -a /etc/cron.d/blocklist_down ]] || [[ ! -a /lib/systemd/system/blacklist_down.service ]] || [[ ! -a /lib/systemd/system/blacklist_down.timer ]]; then
    CRON
fi

main > "$BLOCKLIST" 2>/dev/null
