#!/bin/bash -e

# This is to run my `brewdate` program once a day through `Automator`

LOGS="/Users/jpartain89/Documents/logs"

[ ! -e "$LOGS" ] && mkdir "$LOGS"

/usr/local/bin/brewdate >>"${LOGS}/brewdate_automator.log" 2>&1
