#!/bin/bash -e

# This builds monit with the --enable-optimized flag set.

if [[ $(uname -s) == 'Darwin' ]]; then
    git_dir=/Users/$(logname)/git
else
    git_dir=/home/$(logname)/git
fi

if [[ ! -e "$git_dir/myfunctions" ]]; then
    git clone https://jpartain89@github.com/jpartain89/myfunctions.git "$git_dir/myfunctions"
fi

. "$git_dir/myfunctions/allunix"

# this is my "no_sudo" function from my allunix file
no_sudo

monit_dir="$git_dir/monit"
required_apps=(
    libtool \
    make \
    automake \
    autoconf \
    bison \
    build-essential \
    gcc-4.9 \
    gcc-4.9-base \
    gcc-4.9-source
)

clean_up () {
    sudo monit reload;
    unset required_apps git_dir monit_dir install_apps monit_make;
    sudo rm -r "$monit_dir";
    exit "$1"
}

trap clean_up SIGHUP SIGINT SIGTERM

monit_git () {
    if [[ ! -e "$monit_dir" ]]; then
        echo ""
        echo "Now cloning monit repo"
        echo ""
        git clone https://tildeslash@bitbucket.org/tildeslash/monit.git "$monit_dir"
    fi
}

install_apps () {
    sudo apt-get install "${required_apps[@]}" -y
}

monit_make () {
    cd "$monit_dir" &&
    git pull &&
    ./bootstrap &&
    ./configure --enable-optimized &&
    make &&
    sudo make install
}

install_apps; monit_git; monit_make; clean_up "$@"
