#!/bin/bash -e

# This builds monit with the --enable-optimized flag set.

function no_sudo ()
    {
        if [[ $EUID == 0 ]]; then
            echo ""
            echo "Sorry, but you can't run as sudo."
            echo ""
            exit 1
        fi
    }

monit_dir=/home/$USER/git/monit
required_apps=(
libtool
make
automake
autoconf
bison
build-essential
gcc-4.9
gcc-4.9-base
gcc-4.9-source
)

if [[ ! -e "$monit_dir" ]]; then
    echo ""
    echo "Monit's git directory is missing."
    echo "Now cloning"
    echo ""
    git clone https://tildeslash@bitbucket.org/tildeslash/monit.git "$monit_dir"
fi

for i in "${required_apps[@]}";
do
    which "$i" >/dev/null
    which_out=$?
    if [[ "$which_out" == "1" ]]; then
        sudo apt-get install "$i" -y
    fi
done
unset i required_apps which_out;

cd "$monit_dir" &&
git pull &&
./bootstrap &&
./configure --enable-optimized &&
make &&
sudo make install &&
unset monit_dir
