#!/bin/bash -e

# script to install domotz onto debian-based machines

function no_sudo ()
    {
        if [[ $EUID == 0 ]]; then
            echo ""
            echo "Sorry, but you can't run as sudo."
            echo ""
            exit 1
        fi
    }

if [ ! -e /opt/domotz ]; then
    wget https://portal.domotz.com/download/agent_packages/domotz-box-x64.deb
    sudo dpkg -i domotz-box-x64.deb
fi
