#!/usr/bin/env bash
set -e

tmp="$(mktemp)"
echo "This next step can take a while..."
if [[ $(sudo apt-get update 2>&1 | sed -En 's/.*DEPRECATION*//p' >/dev/null) ]]; then
    echo "An old, untrusted and deprecated gpg key is around here somewhere..."
    echo "Run 'apt-get update' to find it"
    exit 1
fi
sudo apt-get update 2>&1 | sed -En 's/.*NO_PUBKEY ([[:xdigit:]]+).*/\1/p' | sort -u > "${tmp}"
cat "${tmp}" | xargs sudo gpg --keyserver "hkps://keyserver.ubuntu.com:443" --recv-keys # to /usr/share/keyrings/*
cat "${tmp}" | xargs -L 1 sh -c 'sudo gpg --yes --output "/etc/apt/trusted.gpg.d/$1.gpg" --export "$1"' sh # to /etc/apt/trusted.gpg.d/*\
rm "${tmp}"
