#!/usr/bin/env bash

#exec 1> >(logger -s -t "$(basename "$0")") 2>&1

LOC=(
  /Volumes/8TB_EXT/Downloads/Music
  /Volumes/8TB_EXT/iTunes/Music
  )

find "${LOC[@]}" -iname "*.flac" -exec echo {} \; | while IFS= read -r line; do
    ffmpeg -i "$line" -qscale:a 0 "${line[@]/%flac/mp3}"
done
