#!/usr/bin/env bash

while IFS= read -r line; do
    for a in "${line}"; do
        ffmpeg -i "$a" -qscale:a 0 "${a[@]/%flac/mp3}"
    done
done < <(find /Volumes/8TB_EXT/Downloads/Music -iname "*.flv" -exec echo {} \;)
