#!/bin/bash

# Script to auto-clone the generalrepo git repo, along with copying the git map
# code. And any other repo I want auto-added.

DIR=$(dirname "$(readlink -f "$0")")
GIT_DIR=/home/jpartain89/git
source "$GIT_DIR/generalscripts/myfunctions/allunix"
USER=jpartain89

main ()
    {
        git-repos && os_type
    }

linux-function ()
    {
        linux-dotfiles
    }

macOS-function ()
    {
        exit 0
    }

yes_sudo && main
