#!/bin/bash

# Script to auto-clone the generalrepo git repo, along with copying the git map
# code. And any other repo I want auto-added.

DIR=$(dirname "$(readlink -f "$0")")
GIT_DIR=/home/jpartain89/git
source "$GIT_DIR/generalscripts/myfunctions/allunix"
USER=jpartain89

main ()
    {
        git-repos && os_type
    }

git-repos ()
    {
        # Git clones my "General Scripts" repo recursively with the submodule.
        if [[ ! -e "$GIT_DIR/generalscripts" ]]; then
            git clone --recursive https://jpartain89@github.com/jpartain89/generalscripts.git "$GIT_DIR/generalscripts"
        fi

        # Clones the git-map repo and then copys the program to the right spot
        if [[ ! -f /usr/local/bin/git-map ]]; then
            if [[ ! -e "$GIT_DIR/git-map" ]]; then
                git clone https://github.com/icefox/git-map.git "$GIT_DIR/git-map"
            fi
            sudo cp "$GIT_DIR/git-map/git-map" "/usr/local/bin/git-map"
            sudo chmod +x /usr/local/bin/git-map
        fi

        # Copys the conffiles directory that all my vm's use
        if [[ ! -e "$GIT_DIR/conffiles" ]]; then
            git clone https://jpartain89@github.com/jpartain89/conffiles.git "$GIT_DIR/conffiles"
        fi
    }

linux-dotfiles ()
    {
        if [[ ! -e "$GIT_DIR/linux_dotfiles" ]]; then
            git clone https://jpartain89@github.com/jpartain89/linux_dotfiles.git "$GIT_DIR/linux_dotfiles"
        fi
    }

linux-function ()
    {
        linux-dotfiles
    }

macOS-function ()
    {
        exit 0
    }

yes_sudo && main
