#!/bin/bash -e

FILE_LOC=/Volumes/BigPartition/Movies

while IFS= read -r VIDEO; do

    filename=$(basename "${VIDEO}")
    extension=${filename##*.}
    filename=${filename%.*}

    if [[ ! -f "${filename}.mp4" ]]; then
        while true; do
            read -rp "Processing ${VIDEO}. Proceed? " yn </dev/tty
            case $yn in
                [Yy]* ) break;;
                [Nn]* ) exit;;
                * ) echo "Please answer yes or no.";;
            esac
        done

        HandBrakeCLI -Z "Super HQ 1080p30 Surround" -i "${VIDEO}" -o "${FILE_LOC}/${filename}.tmp.mp4" < /dev/null
        mv "${FILE_LOC}/${filename}.tmp.mp4" "${FILE_LOC}/${filename}.mp4"
        echo ""
    fi
done < <(find "${FILE_LOC}" -iname "*.mkv" )
