#!/bin/bash -e

# This auto-installs homebridge by nfarina
# https://github.com/nfarina/homebridge/

if [[ $(uname -s) == 'Darwin' ]]; then
    echo ""
    echo "Sorry, this only runs on Linux"
    read -r
    exit 1
else
    . /etc/*-release
    if [[ "$ID" != "raspbian" ]]; then
        echo ""
        echo "You ain't running on a Pi... Sorry"
        read -r
        exit 1
    fi
fi

yes_sudo
DIRECTORY=$(pwd)

apt-get install git make gcc libavahi-compat-libdnssd-dev -y

echo ""
echo "Installing Nodejs"
echo "Will run a script first"
read -r "Press Enter to Continue"
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

sudo npm install -g --unsafe-perm homebridge hap-nodejs node-gyp
(cd /usr/lib/node_modules/homebridge/ || cd /usr/local/lib/node_modules/homebridge/) || \
    echo "The /usr/lib/node_modules" \
    echo " --- or --- " \
    echo "/usr/local/lib/node_modules"
    echo "file system doesn't exist, exiting" \
    read -r "Press Enter To Continue"; \
    exit 1
sudo npm install --unsafe-perm bignum
(cd /usr/lib/node_modules/hap-nodejs/node_modules/mdns || cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns) || \
    echo "The cd /usr/local/lib/node_modules/hap-nodejs/node_modules/mdns"
    echo " --- or --- "
    echo "cd /usr/lib/node_modules/hap-nodejs/node_modules/mdns"
    echo "doesn't exist, exiting"
    read -r "Press enter to continue"
    exit 1
sudo node-gyp BUILDTYPE=Release rebuild

cd "$DIRECTORY" || \
    echo "Couldn't return to prior directory, exiting"
    read -r "Press Enter to Continue"
    exit 1
sudo npm install -g --unsafe-perm homebridge

echo ""
echo "Make sure to run homebridge after this exits."
echo "Also, add the monit autostart script to /etc/monit/conf.d"
echo ""
read -r "Press enter to continue"
exit 0
