#!/bin/bash -e

# This script is to download prebuilt binary files from Monit for installation
# rather than compiling from git.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

HTML2TEXT="$(command -v html2text)"
MONIT_HTML="https://mmonit.com/monit/dist/binary/"

if [[ $(uname -s) == 'Darwin' ]]; then
    [[ -z "$HTML2TEXT" ]] && brew install html2text
    OS_VAR="macos-x64"
elif [[ $(uname -s) == 'Linux' ]]; then
    [[ -z "$HTML2TEXT" ]] && sudo apt install html2text -y
    if [[ "$(lsb_release -sd | awk '{print $1}')" == 'Ubuntu' ]]; then
        if [[ $(uname -p) == "x86_64" ]]; then
            OS_VAR="linux-x64"
        else
            OS_VAR="linux-x86"
        fi
    elif [[ "$(lsb_release -sd | awk '{print $1}')" == 'Raspbian' ]]; then
        OS_VAR="linux-arm"
    fi
else
    echo "This script is setup to be used by Debian and Darwin based OS's only"
    exit 1
fi

echo "Now getting the latest released version number from Monit"
MONITVER=$(wget -q ${MONIT_HTML} -O - | html2text | grep DIR | tail -n 1 | tr -d / | awk '{print $2}')

echo ""
echo "The current released version of Monit is $MONITVER"

cd /tmp
wget -O - "${MONIT_HTML}${MONITVER}/monit-${MONITVER}-${OS_VAR}.tar.gz" | tar -zxvf
