#!/usr/bin/env bash
set -e

# Program Info
PROGRAM_NAME="jp-etckeeper"
REPO_NAME="generalscripts"
VERSION="1.0.0"

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
[ -e /usr/local/Cellar ] && export PATH="$PATH:/usr/local/Cellar"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#if (( "$EUID" != 0 )); then
#    echo "This script has to be ran as root"
#    exit 1
#fi

# This "auto-installs" git-auto into /usr/local/bin for ya!
command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

DATE="$(date '+%m-%d-%Y %H:%M:%S')"

cd /etc || exit
sudo -E etckeeper commit "Commiting updates through my script on ${DATE}"
if sudo -E git -C /etc push; then
  echo "Looks like 'git push' worked!"
  exit 0
else
  echo "For some reason, the git push command decided to throw an error!!"
  echo "Hopefully the error message came through! Take care of it before running this again!"
  exit 1
fi
