#!/bin/bash

# Short script to kill all Keybase Services

. "$HOME/git/myfunctions/allunix"

no_sudo

if [[ -e /usr/local/bin/keybase ]]; then
    if [[ $(/usr/local/bin/keybase launchd list | grep pid) != "" ]]; then
        for i in service kbfs updater; do
            keybase launchd stop "keybase.${i}"
        done
    else
        echo "No keybase launchd services are running"
    fi
fi
