#!/bin/bash -e

# This script is for running certbot renew through cron
# It calls `certbot renew`, which renews the certs if they are able to be
# Then, after a successful renewal, it proceeds to call the `auto-git`
## script thats in this same git repo

# Copyright © 2017 JPCDI, JPartain89 and Justin Partain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Program Info
PROGRAM_NAME="letsencrypt_update"
REPO_NAME="generalscripts"
VERSION="1.0.0"

PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SITE="jpcdi.com"
LETSENCRYPT_GIT="/home/jpartain89/git/letsencrypt"
LE_SITE="${LETSENCRYPT_GIT}/live/${SITE}"
LOGDIR="${LETSENCRYPT_GIT}/logs"
LOGFILE="${LOGDIR}/certbot.log"

# This assigns the location of the certbot exec to the variable
CERTBOT="$(command -v certbot)"
AUTO_GIT="${$(command -v auto-git):-${DIR}/auto-git}"

[ ! -e "$LOGDIR" ] && mkdir "$LOGDIR"

# This block calls the renewal as an `if` conditional
# It then calls auto-git once its successful.
function callingAutoGit() {
    if "$CERTBOT" renew --renew-hook /usr/local/bin/after_certbot_renew >>"$LOGFILE" 2>&1; then
        { sudo chown -R jpartain89:jpartain89 "$LETSENCRYPT_GIT";
        "${AUTO_GIT} ${LETSENCRYPT_GIT}"; } >>"$LOGFILE" 2>&1

        # copy the files
        sudo cp "${LE_SITE}/cert.pem" "/etc/ssl/certs/${SITE}.cert.pem"
        sudo cp "${LE_SITE}/fullchain.pem" "/etc/ssl/certs/${SITE}.fullchain.pem"
        sudo cp "${LE_SITE}/privkey.pem" "/etc/ssl/private/${SITE}.privkey.pem"

        # adjust permissions of the private key
        sudo chown :ssl-cert "/etc/ssl/private/${SITE}.privkey.pem"
        sudo chmod 640 "/etc/ssl/private/${SITE}.privkey.pem"
    fi
}

callingAutoGit
