#!/bin/bash -e

# Program Info
PROGRAM_NAME="linux-temp"
REPO_NAME="generalscripts"
VERSION="1.0.0"

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
[ -e /usr/local/Cellar ] && export PATH="$PATH:/usr/local/Cellar"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if (( "$EUID" != 0 )); then
    echo "This script has to be ran as root"
    exit 1
fi

# This "auto-installs" git-auto into /usr/local/bin for ya!
command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

# Copied from https://sh.jpcdi.com/2C8bugB
# These lines are linux-standard locations for getting the GPU and CPU temp readings
gpu=$(/opt/vc/bin/vcgencmd measure_temp | awk -F "[=\']" '{print $2}')
cpu=$(</sys/class/thermal/thermal_zone0/temp)

# These lines, obviously, perform the calculations to get from Celsius to Farhenheit
cpu=$(echo "$cpu / 100 * 0.1" | bc)
cpuf=$(echo "(1.8 * $cpu) + 32" | bc)
gpuf=$(echo "(1.8 * $gpu) + 32" | bc)

echo "$(date) @ $(hostname)"
echo "-------------------------------------------"
echo "GPU => $gpu'C ($gpuf'F)"
echo "CPU => $cpu'C ($cpuf'F)"
