#!/usr/bin/env bash
set -e

# Copyright © 2018-2019 JPCDI, JPartain89 and Justin Partain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script is to be ran by Sonarr automatically upon successful download.
# Must have Subler installed

# Program information
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROGRAM_NAME="mkvnmp4_mac"
REPO_NAME="generalscripts"
VERSION="1.0.0"
INPUT="$1"

TRANSCODE_VID="$(command -v transcode-video)"

die() {
    echo "$program: $1" >&2
    exit "${2:-1}"
}

trap 'die trap called' SIGHUP SIGINT SIGTERM

cd "$(dirname "${INPUT}")" &&
"$TRANSCODE_VID" --mp4 --quick "$INPUT"

for i in refresh emptytrash; do
    curl -X PUT -H "X-Plex-Token: zxSt9iYP4A2xcbFz93gM" "http://127.0.0.1:32400/library/sections/1/${i}" >/dev/null 2>&1
    sleep 5
done

exit 0
