#!/usr/bin/env bash
set -e

# Copyright © 2018-2019 JPCDI, JPartain89 and Justin Partain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script is to be ran by Sonarr automatically upon successful download.
# Must have Subler installed

export PATH="/Users/jpartain89/bin:~/bin:/usr/local/opt/python3/bin:/usr/local/opt/python3/libexec/bin:/usr/local/opt/python@2/bin:/usr/local/opt/python/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Cellar:/usr/local/MacGPG2/bin:/usr/local/opt/go/libexec/bin:/Users/jpartain89/.bashhub/bin"

# Program information
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROGRAM_NAME="mkvnmp4_mac"
REPO_NAME="generalscripts"
VERSION="1.0.0"

# exec 1> >(logger -is -t "$(basename "$0")") 2>&1

die() {
    echo "$program: $1" >&2
    exit "${2:-1}"
}

if [[ "$1" == "/Volumes" ]]; then
  die "No file info passed to the script. Exiting!" 1
elif [[ "$1" == "" ]]; then
  die "Nothing passed to the script, exiting!" 1
else
  INPUT="$1"
fi

TRANSCODE_VID="$(command -v transcode-video)"

trap 'die "trap called" 2' SIGHUP SIGINT SIGTERM

cd "$(dirname "${INPUT}")" &&
if "$TRANSCODE_VID" --mp4 --quick "$INPUT"; then
    rsync -avhP --remove-source-files "$INPUT" "${HOME}/.Trash/" &&
    echo "Moved "$(dirname "${INPUT}")" to the Trash"
fi

for i in refresh emptytrash; do
    curl -X PUT -H "X-Plex-Token: zxSt9iYP4A2xcbFz93gM" "http://127.0.0.1:32400/library/sections/1/${i}" >/dev/null 2>&1
    sleep 5
done

exit 0
