#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -

sudo wget -q -O /etc/apt/sources.list.d/mopidy.list "https://apt.mopidy.com/$(lsb_release -cs).list" &&

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install mopidy mopidy-spotify
