#!/bin/bash -e

# tool to automount mdusa for mark

if [[ "$(ping -c 1 -W 5 192.168.86.111)" == "0" ]]; then
    IPADDRESS=192.168.86.111
    LOCAL=yes
else
    IPADDRESS=mdusa.jpcdi.com
    LOCAL=no
fi

MOUNT_POINT=/Users/$(logname)/mdusa

if [[ ! -e "$MOUNT_POINT" ]]; then
    mkdir "$MOUNT_POINT"
fi

if [[ $(which -s sshfs) == "1" ]] && [[ "$LOCAL" == "no" ]]; then
    brew install sshfs
fi

cleanup () {
    sudo umount "$MOUNT_POINT";
    sudo rm -r "$MOUNT_POINT";
    exit $?
}

error_exit () {
    cleanup;
    exit 1
}

trap error_exit 1 2 15

while [[ $(mount | grep -q "on $MOUNT_POINT" > /dev/null) == 0 ]] && [[ $(ping -c 1 -W 5 mdusa.jpcdi.com) == 0 ]]; do
    if [[ "$LOCAL" == "no" ]]; then
        sshfs -o sshfs_sync,no_readahead,nomap=ignore "jpartain89@$IPADDRESS:/media/externals" ~/mdusa | cleanup
    elif [[ ! -e ~/mdusa/PORN ]] && [[ "$LOCAL" == "yes" ]]; then
        mount -t smbfs "//$IPADDRESS/media/externals" ~/mdusa | cleanup
    else
        cleanup
    fi
    sleep 5
done
