#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEST=/media/2TB_Internal/Videos/PORN

if [ $# -ge 1 ]; then SOURCE="$1"
else
    echo "You need to include the source destination on the command line"
    echo "Exiting..."
    exit 1
fi

while IFS= read -r line; do
    sudo rsync -avhP --remove-source-files "${line}" "${DEST}/XTube/"
done < <(find "$SOURCE" -iname "*XTube*" -exec echo {} \; )

while IFS= read -r line; do
    sudo rsync -avhP --remove-source-files "${line}" "${DEST}/SketchySex/"
done < <(find "$SOURCE" -iname "*SketchySex*" -exec echo {} \; )

while IFS= read -r line; do
    sudo rsync -avhP --remove-source-files "${line}" "${DEST}/YouPorn/"
done < <(find "$SOURCE" -iname "*YouPorn*" -exec echo {} \; )

while IFS= read -r line; do
    sudo rsync -avhP --remove-source-files "${line}" "${DEST}/PornHub/"
done < <(find "$SOURCE" -iname "*PornHub*" -exec echo {} \; )

while IFS= read -r line; do
    sudo rsync -avhP --remove-source-files "${line}" "${DEST}/FratX/"
done < <(find "$SOURCE" -iname "*FratX*" -exec echo {} \; )

while IFS= read -r line; do
    sudo rsync -avhP --remove-source-files "${line}" "${DEST}/XVideos/"
done < <(find "$SOURCE" -iname "*XVideos*" -exec echo {} \; )
