#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROGRAM_NAME="new-mysql-dbstuff"
PROGRAM_LOCATION="${DIR}/${PROGRAM_NAME}"
VERSION="1.0.0"

die() {
    echo "$PROGRAM_NAME: $1" >&2
    exit "${2:-1}"
}

trap 'die $@; exit 1' SIGHUP SIGINT SIGTERM

PARAMS=

while (( "$#" )); do
    case "$1" in
        -u | --user )
            adminUser=$2
            shift 2
            ;;
        -p | --password )
            adminPassword=$2
            shift 2
            ;;
        -- )
            # end argument parsing
            shift
            break
            ;;
        -*|--*= ) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        * ) # preserve positional arguments
            PARAMS="$PARAMS $1"
            shift
            ;;
    esac
done

eval set -- "$PARAMS"

userInput() {
    response=
    read -r -p "Enter the name of the Database: " newDB
    read -r -p "Enter the UserName: " newUser
    echo "Enter the Address for after '@'"
    read -r -p "You can use 'localhost' or '%': " host
    read -r -s -p "Enter the password for the new user: " newPassword
}

mysqlCMDS() {
mysql -u"$adminUser" -p"$adminPassword" << 'EOF'
CREATE DATABASE \`${newDB}\`;
CREATE USER '${newUser}'@'${host}' IDENTIFIED BY '${newPassword}';
GRANT USAGE ON *.* TO '${newUser}'@'${host}' IDENTIFIED BY '${newPassword}';
GRANT ALL privileges ON \`${newDb}\`.*
TO '${newUser}'@'${host}';FLUSH PRIVILEGES;"
EOF
}

userInput && mysqlCMDS
