#!/bin/bash -e

rootAddress="https://www.nifty.org/nifty/gay/"
section="authoritarian/"
mainTitle="brutal-trucker-sex/"
specificTitles="brutal-trucker-sex-"

if [[ -e "$HOME/nifty/authoritarian/" ]]; then
    mkdir "$HOME/nifty/authoritarian/"
fi

n=0

while (( n++ < 27 )); do
    wget -P "$HOME/nifty/authoritarian/" "${rootAddress}${section}${mainTitle}${specificTitles}${n}"
done
