#!/usr/bin/env bash
set -e

PROGRAM_NAME="plexcleaner"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


die() {
  echo "$PROGRAM_NAME: $1" >&2
  exit "${2:-1}"
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
  (
  if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
    sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
    sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
  else
    echo "For some reason, linking ${PROGRAM_NAME} to /usr/local/bin,"
    echo "failed. My apologies for not being able to figure it out..."
    exit 1
    fi
  )
}

DOCKER=$(command -v docker)
VOLUME="/media:/media"
IMAGE="docker.io/ptr727/plexcleaner"
CMD="/PlexCleaner/PlexCleaner"

CLI="run \
  -it \
  --rm \
  --pull always \
  --log-driver json-file --log-opt max-size=10m \
  --name PlexCleaner \
  --user nobody:users \
  --env TZ=America/Chicago \
  --volume /media:/media \
  --volume /docker/PlexCleaner:/docker/PlexCleaner \
  ${IMAGE} \
    ${CMD} --settingsfile /docker/PlexCleaner/PlexCleaner.json \
    --logfile /docker/PlexCleaner/PlexCleaner.log \
    --logwarning \
    process \
    --parallel \
    --mediafiles /media/Movies \
    --mediafiles /media/Porn \
    --mediafiles /media/TV \
    --mediafiles /media/8TB/Porn"

${DOCKER} ${CLI} "$@"
