#!/usr/bin/env bash -e

# This script is to test if my externals are mounted or not, and if not, remount them

for i in 8TB_EXT 2TB_APFS; do
    if [ "$(/bin/mount | grep -c "/media/$i")" ]; then
        echo "already mounted"
    else
        { sudo umount "/media/$i" &&
        sudo mount "/media/$i"
            } || { echo "mounting failed" &&
            exit 1
                }
    fi
done
