#!/usr/bin/env bash

# Script to install Security Onion

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ISO_LOC="/media/server1/TechStuff/System Images_Files"

cd "${ISO_LOC}" &&
wget  https://github.com/Security-Onion-Solutions/security-onion/releases/download/v14.04.5.11_20180328/securityonion-14.04.5.11.iso &&

wget  https://github.com/Security-Onion-Solutions/security-onion/raw/master/sigs/securityonion-14.04.5.11.iso.sig &&

wget  https://raw.githubusercontent.com/Security-Onion-Solutions/security-onion/master/KEYS &&

gpg --import "./KEYS" &&
gpg --verify "./securityonion-14.04.5.11.iso.sig" "./securityonion-14.04.5.11.iso"
