#!/bin/bash -e

# Script to shutdown and turn off MariaDB

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


function stopMaria() {
    if sudo service mysql stop; then
        sudo systemctl disable mariadb.service >/dev/null 2>&1
        sudo update-rc.d mysql remove
    fi
}

function startMaria() {
    sudo systemctl enable mariadb.service >/dev/null 2>&1
    sudo update-rc.d mysql defaults
    sudo service mariadb start
}

case "$1" in
    --start )
        startMaria;
        exit 0;;
    --stop )
        stopMaria;
        exit 0;;
    * )
        echo "You need to use one of the options: ";
        echo "--start or --stop";
        exit 1;;
esac
