#!/usr/bin/env bash
set -e

PROGRAM_NAME=start_docker_containers
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARAMS=""

DOCKER_FILE_LOCATION="${HOME}/git/docker_directory"
DOCKER_FILE=docker-compose.yml
DOCKER_FILE_CHILD_LOCATIONS=(
  .
  authentik
  duplicati
  grafana
  paperless-ng
  snipeit
  unpoller
)

die() {
    echo "$PROGRAM_NAME: $1" >&2
    exit "${2:-1}"
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

eval $(op signin)
for i in "${DOCKER_FILE_CHILD_LOCATIONS[@]}"; do
    if [[ -e "${DOCKER_FILE_LOCATION}/${i}/.env.tpl" ]]; then
        op inject -i "${DOCKER_FILE_LOCATION}/${i}/.env.tpl" -o "${DOCKER_FILE_LOCATION}/${i}/.env"
    elif [[ -e "${DOCKER_FILE_LOCATION}/${i}/docker-compose.env.tpl" ]]; then
        op inject -i "${DOCKER_FILE_LOCATION}/${i}/docker-compose.env.tpl" -o "${DOCKER_FILE_LOCATION}/${i}/docker-compose.env"
    fi

  docker compose -f "${DOCKER_FILE_LOCATION}/${i}/${DOCKER_FILE}" pull &&
  docker compose -f "${DOCKER_FILE_LOCATION}/${i}/${DOCKER_FILE}" up -d
done

