#!/bin/bash -e

# Script to shutdown and turn off MariaDB

# Keep-alive: update existing sudo time stamp if set, otherwise do nothing.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


function stopMaria() {
    if service mysql stop; then
        systemctl disable mariadb.service >/dev/null 2>&1
        update-rc.d mysql remove
    fi
}

function startMaria() {
    systemctl enable mariadb.service >/dev/null 2>&1
    update-rc.d mysql defaults
    service mariadb start
}

while [ $# -ge 1 ]; do
    case "$1" in
        --start )
            startMaria;
            exit 0;;
        --stop )
            stopMaria;
            exit 0;;
        * )
            echo "You need to use one of the options: ";
            echo "--start or --stop";
            exit 1;;
    esac
done
