#!/bin/bash -e

BACKUP_IP="192.168.1.15"

tar -cvpz \
    --exclude=/proc \
    --exclude=/tmp \
    --exclude=/mnt \
    --exclude=/dev \
    --exclude=/sys \
    --exclude=/lost+found \
    --exclude=/run \
    --exclude=/media \
    --exclude=/var/log \
    --exclude=/var/cache/apt/archives \
    --exclude=/usr/src/linux-headers* \
    --exclude=/home/*/.gvfs \
    --exclude=/home/*/.cache \
    --exclude=/home/*/.local \
    --exclude=/home/*/.local/share/Trash / | nc -q 0 "$BACKUP_IPBACKUP_IP" 1024
