#!/usr/bin/env bash

# Retrieves missing keys from keyserver.ubuntu.com from user-input pubkey.
# The "pubkey" is the string of letters and numbers that apt-get will spit out
# when the private key isn't saved. Its the "public key," thus "pubkey."

CLI=( "$@" )

if [[ "$#" -ge 1 ]]; then
    for apps in "${CLI[@]}"; do
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys "${apps}"
    done
else
    read -r "Paste in the GPG Key that needs to be retrieved: " gpgkey
    while IFS= read -r file; do
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys "$file"
    done < <(${gpgkey})
fi
