#!/bin/bash -e

REPOGITDIR=$(git rev-parse --git-dir 2> /dev/null)
if [ $? -eq 0 ] ; then
    cd "${REPOGITDIR}/../../"
fi

find . -maxdepth 2 -type d -name .git -prune -exec dirname '{}' \; |
while read -r dir; do
    cd "${dir}"
    if [[ "$(git remote -v)" == *"jpartain89"* ]]; then
        if [[ "$(git remote -v)" != *"git@github"* ]]; then
            echo "Updating ${dir} now!"
            git remote -v
            echo "to"
            echo "git@github.com:jpartain89/${nDIR}"
            nDIR="${dir#./}"
            git remote set-url origin "git@github.com:jpartain89/${nDIR}"
            git pull || continue
        fi
    fi
    cd "${REPOGITDIR}/../../"
done
