#!/usr/bin/env bash

# Retrieves missing keys from keyserver.ubuntu.com from user-input pubkey.
# The "pubkey" is the string of letters and numbers that apt-get will spit out
# when the private key isn't saved. Its the "public key," thus "pubkey."

CLI=( "$@" )

if [[ "$#" -ge 1 ]]; then
    for apps in "${CLI[@]}"; do
        sudo gpg --no-default-keyring \
          --keyring /usr/share/keyrings/catchall.gpg \
           --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "${apps}"
    done
else
    read -p "Paste in the GPG Key that needs to be retrieved: " gpgkey
    while IFS= read -r file; do
        sudo gpg --no-default-keyring \
          --keyring /usr/share/keyrings/catchall.gpg \
          --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$file"
    done < <(${gpgkey})
fi
