#! /bin/bash

# Userify shim Installation
# Company: JPCDI
# Project: RPI1

# Paste this one-liner into your server console.
# It only needs to be done once per server (or image).

#! /bin/bash
curl -1 -sS "https://static.userify.com/installer.sh" | \
    api_key="oywCvpaPyBkN8fXULPAtWdir8CDzwemH9fiXWNynUf3oDgwZyE" \
    api_id="sph5bvxatpjwaqmv4dyey7_user" \
    company_name="JPCDI" \
    project_name="RPI1" \
    static_host="static.userify.com" \
    shim_host="configure.userify.com" \
    self_signed=0 \
    sudo -sE
