#!/bin/bash

# TODO: Add awk line to remove link from yt.txt file when download is finished and removed, and to reload the script to re-pull the correct links

# Copyright © 2017-2019 JPCDI, JPartain89 and Justin Partain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# program info
PROGRAM_NAME="yt-porn"
REPO_NAME="generalscripts"
VERSION="1.5.0"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

die() {
    echo "$PROGRAM_NAME: $1" >&2
    exit "${2:-1}"
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

help() {
    cat << EOF

Usage: yt-porn [ -f | --file ] [ arguments ]

    yt-porn is meant to download porn videos and automatically move them to the porn directory.

    The script also auto-installs axel downloading program.

    -f | --file :   This specifies that the videos you want downloaded are
                    saved inside a text file, each on their own lines

EOF
exit 1
}

command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

# These confirm that the required programs are installed
YTDL="$(command -v youtube-dl)"
if [[ -e "$(command -v axel)" ]]; then
    AXEL="$(command -v axel)"
else
    if [[ "$(uname)" == "Darwin" ]]; then
        brew install axel &&
        AXEL="$(command -v axel)"
    elif [[ $(uname) == "Linux" ]]; then
        sudo apt-get install axel
        AXEL="$(command -v axel)"
    fi
fi

test -x "${YTDL}" || die "Looks like $PROGRAM_NAME is missing."

move() {
    unsorted=/media/2TB_APFS/Porn/Unsorted
    rsync -avhP --remove-source-files "${fileORIGINAL}" "${unsorted}/${fileNAME}"
}

file() {
    if [[ "$(cat "$2")" == "" ]]; then
        die "File was empty"
    else
        PORN_FILE="$2"
    fi
    while IFS= read -r file; do
        for i in $file; do
            URL="$i"
            fileORIGINAL="$("$YTDL" "$i" --get-filename)"
            fileNAME="$(basename "${fileORIGINAL}")"
            "${YTDL}" "${i}" &&
            if [[ $move == 1 ]]; then
                move
            else
                echo "The downloaded file is at"
                echo "${fileORIGINAL}"
            fi

            # This replaces URL with `  `
            sed -i '' "s|${URL}|  |g" "${PORN_FILE}"
        done
    done< <(cat "${PORN_FILE}")
}

single() {
    fileORIGINAL="$("$YTDL" "$CLI_URL" --get-filename)"
    fileNAME="$(basename "${fileORIGINAL}")"
    "${YTDL}" "${CLI_URL}" &&
    if [[ $move == 1 ]]; then
        move
    fi
}

if [ "$?" == -m ] || [ "$?" == --move ]; then
    move=1
fi

if [ $# == 0 ]; then
  help
fi

while [ $# -gt 1 ]; do
    case "$1" in
        -f | --file )
            file "$@"; shift;;
        -s | --single )
            CLI_URL="$2";
            single;;
    esac
done
