#!/bin/bash -e

PROGRAM_NAME="yt-porn"
REPO_NAME="generalscripts"
VERSION="1.0.0"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

die() {
    echo "$PROGRAM_NAME: $1" >&2
    exit "${2:-1}"
}

trap "die 'trap called'" SIGHUP SIGINT SIGTERM

command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
    (
        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
        else
            echo "For some reason, linking $PROGRAM_NAME to /usr/local/bin,"
            echo "failed. My apologies for not being able to figure it out..."
            exit 1
        fi
    )
}

YT_DL="$(command -v youtube-dl)"

text -x "${YT_DL}" || die "Looks like $PROGRAM_NAME is missing."

[ -n "$1" ] || help_text && exit 1

file() {
    while IFS= read -r file; do
        for i in $file; do
            "$YT_DL" "'$i'"
        done
    done< <(cat "$2")
}

while [ $# -ge 1 ]; do
    case "$1" in
        -f | --file )
            file"$@";;
        -s | --single )
            single;;
        * )
            die;;
    esac
done
